### ISSUE TITLE
monetdblite.init giving segfault if already initialized 

### ISSUE THREAD

**Issue by danigosa** [hannesmuehleisen/MonetDBLite-Python#25]
Would it be better an Exception?

**Comment by danigosa** [comment]
It's the latest from pypi 0.6.0.post6

**Comment by hannesmuehleisen** [comment]
@kutsurak can you have a look please? @danigosa happy to review a version number PR.

**Comment by kutsurak** [comment]
Sure, I will work on this, but please keep in mind that it might take some time because we are preparing a demo for next week.

**Comment by danigosa** [comment]
Hi @kutsurak, for now we are circumventing this by using a single process and threading (creating a new connection `Connection` by hand as `monetdblite.connect` is returning `PyClient`) but of course on multiprocessing (just to name one, on gunicorn) it's not possible to init same folder on several processes (error indicating `cannot lock file xxxx` or similar). It would be really interesting that more than one process can init the db, as it's common and old pattern to fork processes to leverage on multi-core in Python.

**Comment by kutsurak** [comment]
Hey @danigosa. This PR introduces a new function `monetdblite.make_connection` that returns a `Connection` object. This is unfortunate, but necessary (for now) because the README says clearly that the program in #22 should work. We need to make the API a bit more consistent, but I have no timeline to give you for when this will happen.

As for the multiprocess initialization of the db, I am pretty sure that the design of MonetDB itself does not allow this. As far as I understand it the reason is that `monetdblite.init` essentially starts a (Lite) MonetDB server, serving the database at the specified directory. There cannot be two different MonetDB server processes serving the same files, because transaction control in MonetDB is implemented in the context of the server process. Essentially each server process does not know about the other, and if they both need to perform an `INSERT` in the same table at the same time, you end up with inconsistent database files.

You can of course have multiple client processes, i.e. make `Connection` objects and use `Cursor`s (`Connection.cursor()`) to interact with the database.

**Comment by danigosa** [comment]
@kutsurak interesting, it's obvious that if embedded process is in its own python process other processes would not be able to. As a question: is then possible to connect with `Connection` (I saw it has host, port, etc. params) to a fully fledged MonetDB server and then continue to use monetdblite for python with it's cursor numpy API?

**Comment by kutsurak** [comment]
Hey @danigosa. The answer to your question is unfortunately no: This part of the `Connection` object (using host, port etc) is not implemented. I have not talked with @hannesmuehleisen about it, but I believe that they should be removed from the signature of the constructor, because they do not make sense (to me at least) in the context of MonetDBLite.

**Comment by danigosa** [comment]
@kutsurak got it, it actually makes more sense to add to the _official_ MonetDB python driver the `numpy` cursor functionality than on the _Lite_.
